heat_template_version: 2021-04-16

description:
  Root stack for OpenStack IaaS deployment for CCT

parameters:
  webserver_port:
    type: number
    description: Network port for the webserver instance

  webserver_floating_ip:
    type: string
    description: Floating IP for the webserver instance

  db_flavor:
    type: string
    description: Flavor for the db instance

  webserver_flavor:
    type: string
    description: Flavor for the webserver instance

  keypair_public_key:
    type: string
    description: Public key associated to the pre-existing keypair


resources:
  demo_networking:
    type: OS::DemoCCT::Networking
    properties:
      webserver_port: { get_param: webserver_port }
      webserver_floating_ip: { get_param: webserver_floating_ip }

  demo_computing:
    type: OS::DemoCCT::Computing
    properties:
      network_id: { get_attr: [demo_networking, network_id] }
      db_port: { get_attr: [demo_networking, db_port] }
      db_flavor: { get_param: db_flavor }
      webserver_port: { get_attr: [demo_networking, webserver_port] }
      webserver_flavor: { get_param: webserver_flavor }
      keypair_public_key: { get_param: keypair_public_key }
