AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RetrieveAccountLambdaArn:
    Type: String
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: apigw-demo-cct
      Tags:
        - Key: Environment
          Value: demo-cct-paas
  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !GetAtt RestApi.RootResourceId
      HttpMethod: GET
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: '200'
          ResponseParameters:
            method.response.header.Content-Type: false
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RetrieveAccountLambdaArn}/invocations
        IntegrationResponses:
          - StatusCode: '200'
            SelectionPattern: ''
            ResponseParameters:
              method.response.header.Content-Type: '''text/html'''
            ResponseTemplates:
              text/html: $input.path("$")
  Deployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiMethod
    Properties:
      RestApiId: !Ref RestApi
      StageName: demo-cct
Outputs:
  ApiGatewayEndpoint:
    Description: The endpoint to connect to the API Gateway
    Value: !Sub https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/demo-cct