apiVersion: 1

datasources:
  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    # jsonData:
    #   httpHeaderName1: "X-Scope-OrgID"
    # secureJsonData:
    #   httpHeaderValue1: "tenant1"