Description: >
  CloudFormation template for deploying the MySQL instance within the cct demo on iaas

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair used to SSH into the instance
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet where the instance will be launched
  SecGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for the instance
  PrivateIpAddress:
    Type: String
    Default: '10.0.0.7'
    Description: Fixed IP address of the DB instance. By fixing it, the webserver knows in advance how to reach it

Outputs:
  SqlInstanceIpAddress:
    Description: IP address of the Sql instance created
    Value: !GetAtt SqlDbInstance.PrivateIp

Resources:
  SqlDbLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        # Debian 12
        ImageId: ami-0ef32de3e8ab0640e
        InstanceType: t2.medium
        KeyName: !Ref KeyPairName
        Monitoring:
          Enabled: true
        NetworkInterfaces:
          - AssociatePublicIpAddress: false
            DeviceIndex: 0
            SubnetId: !Ref SubnetId
            Groups:
              - !Ref SecGroupId
            PrivateIpAddress: !Ref PrivateIpAddress
        UserData: 
          Fn::Base64: |
            #cloud-config
            #
            # provisioning script of mysql db for debian-based distro
            package_reboot_if_required: true
            package_update: true
            package_upgrade: true
            packages:
              - gnupg

            write_files:
            - content: |
                CREATE DATABASE cct;
                CREATE USER 'cct'@'%' IDENTIFIED BY 'cct-secret';
                GRANT ALL PRIVILEGES ON cct.* TO 'cct'@'%';
                FLUSH PRIVILEGES;
              path: /init.sql

            runcmd:
              - [wget, "https://dev.mysql.com/get/mysql-apt-config_0.8.33-1_all.deb"]
              - export DEBIAN_FRONTEND=noninteractive && dpkg -i mysql-apt-config_0.8.33-1_all.deb
              - rm mysql-apt-config_0.8.33-1_all.deb
              - apt update
              - apt -y install mysql-server
              - mysql -u root < /init.sql
              - [wget, "https://raw.githubusercontent.com/Sesar-Lab-Teaching/Cloud-Computing-Technologies/refs/heads/main/sqldb/seed.sql"]
              - mysql -u cct --password=cct-secret cct < seed.sql
              - rm seed.sql
              - systemctl restart mysql
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: demo-cct-mysql-instance
  SqlDbInstance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref SqlDbLaunchTemplate
        Version: !GetAtt SqlDbLaunchTemplate.DefaultVersionNumber