Parameters:
  ECRSeedDbLambdaRepository:
    Description: ECR repository uri for the lambda seed-db
    Type: String
  ECRGetDataLambdaRepository:
    Description: ECR repository uri for the lambda get-data
    Type: String
  DbName:
    Description: database name
    Type: String
    Default: democct
  DbUsername:
    Description: db instance username
    Type: String
    Default: demouser
  DbPassword:
    Description: db instance password
    Type: String
    Default: demopassword

Outputs:
  SeedDbLambdaArn:
    Description: Arn of the Lambda that seeds the Db
    Value: !GetAtt SeedDbLambdaStack.Outputs.LambdaArn
  ApiGatewayEndpoint:
    Description: Endpoint of the api gateway
    Value: !GetAtt ApiGateway.Outputs.Endpoint

Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://demo-cct1.s3.eu-central-1.amazonaws.com/paas/cfn-templates/networking.yaml'
      Tags:
        - Key: Environment
          Value: demo-cct-paas

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://demo-cct1.s3.eu-central-1.amazonaws.com/paas/cfn-templates/db.yaml'
      Tags:
        - Key: Environment
          Value: demo-cct-paas
      Parameters:
        DbName: !Ref DbName
        DbUsername: !Ref DbUsername
        DbPassword: !Ref DbPassword
        SecGroup: !GetAtt NetworkingStack.Outputs.SecGroup
        Subnet1Id: !GetAtt NetworkingStack.Outputs.Subnet1Id
        Subnet2Id: !GetAtt NetworkingStack.Outputs.Subnet2Id

  AuthorizationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://demo-cct1.s3.eu-central-1.amazonaws.com/paas/cfn-templates/authorization.yaml'
      Tags:
        - Key: Environment
          Value: demo-cct-paas

  SeedDbLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://demo-cct1.s3.eu-central-1.amazonaws.com/paas/cfn-templates/seed-db-lambda.yaml'
      Tags:
        - Key: Environment
          Value: demo-cct-paas
      Parameters:
        ECRLambdaRepository: !Ref ECRSeedDbLambdaRepository
        RoleArn: !GetAtt AuthorizationStack.Outputs.LambdaRoleArn
        SecGroup: !GetAtt NetworkingStack.Outputs.SecGroup
        Subnet1Id: !GetAtt NetworkingStack.Outputs.Subnet1Id
        Subnet2Id: !GetAtt NetworkingStack.Outputs.Subnet2Id
        DbName: !Ref DbName
        DbUsername: !Ref DbUsername
        DbPassword: !Ref DbPassword
        DbEndpoint: !GetAtt RDSStack.Outputs.Endpoint
        DbPort: !GetAtt RDSStack.Outputs.Port

  GetDataLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://demo-cct1.s3.eu-central-1.amazonaws.com/paas/cfn-templates/get-data-lambda.yaml'
      Tags:
        - Key: Environment
          Value: demo-cct-paas
      Parameters:
        ECRLambdaRepository: !Ref ECRGetDataLambdaRepository
        RoleArn: !GetAtt AuthorizationStack.Outputs.LambdaRoleArn
        SecGroup: !GetAtt NetworkingStack.Outputs.SecGroup
        Subnet1Id: !GetAtt NetworkingStack.Outputs.Subnet1Id
        Subnet2Id: !GetAtt NetworkingStack.Outputs.Subnet2Id
        DbName: !Ref DbName
        DbUsername: !Ref DbUsername
        DbPassword: !Ref DbPassword
        DbEndpoint: !GetAtt RDSStack.Outputs.Endpoint
        DbPort: !GetAtt RDSStack.Outputs.Port
    
  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://demo-cct1.s3.eu-central-1.amazonaws.com/paas/cfn-templates/api-gateway.yaml'
      Tags:
        - Key: Environment
          Value: demo-cct-paas
      Parameters:
        GetDataLambdaArn: !GetAtt GetDataLambdaStack.Outputs.LambdaArn
