AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  ECRSeedDbLambdaRepository:
    Description: ECR repository uri for the lambda seed-db
    Type: String

  ECRGetDataLambdaRepository:
    Description: ECR repository uri for the lambda get-data
    Type: String

  DbName:
    Description: database name
    Type: String
    Default: democct

  DbUsername:
    Description: db instance username
    Type: String
    Default: demouser

  DbPassword:
    Description: db instance password
    Type: String
    Default: demopassword


Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/networking.yaml
      Tags:
        - Key: Environment
          Value: demo-cct-paas

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/db.yaml
      Tags:
        - Key: Environment
          Value: demo-cct-paas
      Parameters:
        DbName: !Ref DbName
        DbUsername: !Ref DbUsername
        DbPassword: !Ref DbPassword
        DbSecGroupIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.DbSecGroupId ] ]
        DbSubnetIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.PrivateSubnet1Id, !GetAtt NetworkingStack.Outputs.PrivateSubnet2Id ] ]

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/lambda.yaml
      Tags:
        - Key: Environment
          Value: demo-cct-paas
      Parameters:
        ECRSeedDbLambdaRepository: !Ref ECRSeedDbLambdaRepository
        ECRGetDataLambdaRepository: !Ref ECRGetDataLambdaRepository
        LambdaSecGroupIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.DbSecGroupId ] ]
        LambdaSubnetIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.PrivateSubnet1Id, !GetAtt NetworkingStack.Outputs.PrivateSubnet2Id ] ]
        DbName: !Ref DbName
        DbUsername: !Ref DbUsername
        DbPassword: !Ref DbPassword
        DbEndpoint: !GetAtt RDSStack.Outputs.Endpoint
    
  ApiGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/api-gateway.yaml
      Tags:
        - Key: Environment
          Value: demo-cct-paas
      Parameters:
        GetDataLambdaArn: !GetAtt LambdaStack.Outputs.GetDataLambdaArn


Outputs:
  SeedDbLambdaArn:
    Description: Arn of the Lambda that seeds the Db
    Value: !GetAtt LambdaStack.Outputs.SeedDbLambdaArn
    
  ApiGatewayEndpoint:
    Description: Endpoint of the api gateway
    Value: !GetAtt ApiGateway.Outputs.Endpoint