receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'
      http:
        endpoint: '0.0.0.0:4318'
  docker_stats:
    # default endpoint: unix:///var/run/docker.sock
    collection_interval: 10s
    initial_delay: 15s
    timeout: 10s

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: '0.0.0.0:8889'
    metric_expiration: '30m'
  otlp_grpc/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
    sending_queue:
      batch:
        flush_timeout: 10s

extensions:
  health_check:
    endpoint: '0.0.0.0:13133'
  pprof:
    endpoint: '0.0.0.0:1777'
  zpages:
    endpoint: '0.0.0.0:55679'

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
    # logs:
    #   processors:
    #     - batch:
    #         exporter:
    #           otlp:
    #             protocol: http/protobuf
    #             endpoint: https://backend:4318
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp_grpc/jaeger]
    metrics:
      receivers: [otlp, docker_stats]
      exporters: [prometheus]
    # logs:
    #   receivers: [otlp]
    #   exporters: [otlp_grpc]