# syntax=docker/dockerfile:1

FROM public.ecr.aws/lambda/python:3.12

# LAMBDA_TASK_ROOT is the root folder in the runtime environment
COPY requirements.txt ${LAMBDA_TASK_ROOT}

RUN pip install -r requirements.txt

COPY lambda_seed_db.py ${LAMBDA_TASK_ROOT}

CMD ["lambda_seed_db.handler"]