Description: CloudFormation template for deploying the Lambda that will seed the DB

Parameters:
  ECRLambdaRepository:
    Description: ECR repository uri for the lambda
    Type: String
  RoleArn:
    Description: Arn of the Lambda role
    Type: String
  SecGroup:
    Description: VPC Security group of the Lambda
    Type: String
  Subnet1Id:
    Description: The ID of the Subnet 1 within the VPC
    Type: String
  Subnet2Id:
    Description: The ID of the Subnet 2 within the VPC
    Type: String
  DbName:
    Description: The name of the database
    Type: String
  DbUsername:
    Description: username to access the db
    Type: String
  DbPassword:
    Description: password to access the db
    Type: String
  DbEndpoint:
    Description: endpoint used to access the db instance
    Type: String
  DbPort:
    Description: Port of the Db instance
    Type: String

Outputs:
  LambdaArn:
    Description: Arn of the created Lambda
    Value: !GetAtt SeedDbLambda.Arn

Resources:
  SeedDbLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        ImageUri: !Ref ECRLambdaRepository
      Environment:
        Variables:
          MYSQL_HOST: !Ref DbEndpoint
          MYSQL_USER: !Ref DbUsername
          MYSQL_PASSWORD: !Ref DbPassword
          MYSQL_DATABASE: !Ref DbName
          MYSQL_PORT: !Ref DbUsername
      FunctionName: demo-cct-lambda-seed-db
      PackageType: Image
      Role: !Ref RoleArn
      Timeout: 20
      VpcConfig: 
        SecurityGroupIds: 
          - !Ref SecGroup
        SubnetIds: 
          - !Ref Subnet1Id
          - !Ref Subnet2Id