#cloud-config
#
# provisioning script of mysql db for debian-based distro
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - gnupg

write_files:
- content: |
    CREATE DATABASE cct;
    CREATE USER 'cct'@'%' IDENTIFIED BY 'cct-secret';
    GRANT ALL PRIVILEGES ON cct.* TO 'cct'@'%';
    FLUSH PRIVILEGES;
  path: /init.sql

runcmd:
  - [wget, "https://dev.mysql.com/get/mysql-apt-config_0.8.33-1_all.deb"]
  - export DEBIAN_FRONTEND=noninteractive && dpkg -i mysql-apt-config_0.8.33-1_all.deb
  - rm mysql-apt-config_0.8.33-1_all.deb
  - apt update
  - apt -y install mysql-server
  - mysql -u root < /init.sql
  - [wget, "https://raw.githubusercontent.com/Sesar-Lab-Teaching/Cloud-Computing-Technologies/refs/heads/main/sqldb/seed.sql"]
  - mysql -u cct --password=cct-secret cct < seed.sql
  - rm seed.sql
  - systemctl restart mysql
