AWSTemplateFormatVersion: '2010-09-09'


Description: Api Gateway for the Lambda invocation


Parameters:
  GetDataLambdaArn:
    Description: Arn of the Lambda that gets account data
    Type: String


Resources:
  # ------------------------ API Gateway (HTTP)
  # Two types of gateway exists, REST API and HTTP API. They are both RESTful, but REST APIs support more features than HTTP APIs.
  # However, HTTP APIs are cheaper.
  HTTPApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      ProtocolType: HTTP
      Name: demo-cct-paas-apigw

  GetDataLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HTTPApi
      PassthroughBehavior: WHEN_NO_MATCH
      # Same as Lambda Timeout
      TimeoutInMillis: 20000
      IntegrationMethod: POST
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDataLambdaArn}/invocations"

  # ------------------------ Route for GET /accounts.html
  GetDataRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HTTPApi
      AuthorizationType: NONE
      RouteKey: "GET /accounts.html"
      Target: !Sub 'integrations/${GetDataLambdaIntegration}'

  # ------------------------ Deployment
  # A deployment is a snapshot of the API configuration. You must create a deployment to make your API callable
  ApiDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - GetDataRoute
    Properties:
      Description: API Deployment for Demo CCT on PaaS
      ApiId: !Ref HTTPApi

  # A stage is a named reference to a deployment. Multiple stages can reference the same deployment, but each stage (prod, stage) is configured independently
  # and possibly with different variable.
  ApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      DeploymentId: !Ref ApiDeployment
      Description: Stage v1
      ApiId: !Ref HTTPApi
      StageName: "v1"


Outputs:
  Endpoint:
    Description: The endpoint to connect to the API Gateway
    Value: !Sub 
      - '${ApiGatewayUrl}/${ApiStage}'
      - ApiGatewayUrl: !GetAtt HTTPApi.ApiEndpoint
