AWSTemplateFormatVersion: '2010-09-09'


Description: template for deploying the network 


Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.20.0.0/23

  # ------------------------ Subnets
  # an RDS instance must be deployed on 2 subnets within different AZs
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.20.0.0/24
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.20.1.0/24
      AvailabilityZone: 
        Fn::Select: 
          - 1
          - Fn::GetAZs: ""

  # ------------------------ Security Groups
  DbSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: demo-cct-paas-db-sec-group
      GroupDescription: Security group for db instance
      VpcId: !Ref VPC

  DbSecGroupAllowFromSameSecGroupRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow connections within same Security group to port 3306
      GroupId: !Ref DbSecGroup
      FromPort: 3306
      IpProtocol: tcp
      ToPort: 3306
      SourceSecurityGroupId: !Ref DbSecGroup


Outputs:
  PrivateSubnet1Id:
    Description: The ID of the Private Subnet 1
    Value: !Ref PrivateSubnet1

  PrivateSubnet2Id:
    Description: The ID of the Private Subnet 2
    Value: !Ref PrivateSubnet2

  DbSecGroupId:
    Description: Security group for db instance
    Value: !Ref DbSecGroup