AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  DbCloudInitConfig:
    Type: String
    Description: Cloud-init configuration for the database instance

  WebServerCloudInitConfig:
    Type: String
    Description: Cloud-init configuration for the webserver instance


Resources:
  DemoCCTNetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/networking.yaml
      Tags:
        - Key: Environment
          Value: demo-cct

  DemoCCTComputingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/computing.yaml
      Tags:
        - Key: Environment
          Value: demo-cct
      Parameters:
        VpcId: !GetAtt DemoCCTNetworkingStack.Outputs.VpcId
        DbCloudInitConfig: !Ref DbCloudInitConfig
        DbSubnetId: !GetAtt DemoCCTNetworkingStack.Outputs.PrivateSubnet1Id
        DbSecGroupIds: !Join [ ",", [ !GetAtt DemoCCTNetworkingStack.Outputs.BaseSecGroupId ] ]
        WebServerCloudInitConfig: !Ref WebServerCloudInitConfig
        WebServerSecGroupIds: !Join [ ",", [ !GetAtt DemoCCTNetworkingStack.Outputs.BaseSecGroupId, !GetAtt DemoCCTNetworkingStack.Outputs.Allow5000SecGroupId ] ]
        LoadBalancerSubnetIds: !Join [ ",", [ !GetAtt DemoCCTNetworkingStack.Outputs.PublicSubnet1Id, !GetAtt DemoCCTNetworkingStack.Outputs.PublicSubnet2Id ] ]
        LoadBalancerSecGroupIds: !Join [ ",", [ !GetAtt DemoCCTNetworkingStack.Outputs.BaseSecGroupId, !GetAtt DemoCCTNetworkingStack.Outputs.AllowHTTPSecGroupId ] ]
        AutoScalingGroupSubnetIds: !Join [ ",", [ !GetAtt DemoCCTNetworkingStack.Outputs.PublicSubnet1Id, !GetAtt DemoCCTNetworkingStack.Outputs.PublicSubnet2Id ] ]
        Route53HostedZone: !GetAtt DemoCCTNetworkingStack.Outputs.Route53HostedZone
