AWSTemplateFormatVersion: '2010-09-09'


Parameters:
  DbCloudInitConfig:
    Type: String
    Description: Cloud-init configuration for the database instance

  WebServerCloudInitConfig:
    Type: String
    Description: Cloud-init configuration for the webserver instance


Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/networking.yaml
      Tags:
        - Key: Environment
          Value: demo-cct-iaas

  ComputingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./modules/computing.yaml
      Tags:
        - Key: Environment
          Value: demo-cct-iaas
      Parameters:
        VpcId: !GetAtt NetworkingStack.Outputs.VpcId
        DbCloudInitConfig: !Ref DbCloudInitConfig
        DbSubnetId: !GetAtt NetworkingStack.Outputs.PrivateSubnet1Id
        DbSecGroupIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.BaseSecGroupId ] ]
        WebServerCloudInitConfig: !Ref WebServerCloudInitConfig
        WebServerSecGroupIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.BaseSecGroupId, !GetAtt NetworkingStack.Outputs.Allow5000SecGroupId ] ]
        LoadBalancerSubnetIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.PublicSubnet1Id, !GetAtt NetworkingStack.Outputs.PublicSubnet2Id ] ]
        LoadBalancerSecGroupIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.BaseSecGroupId, !GetAtt NetworkingStack.Outputs.AllowHTTPSecGroupId ] ]
        AutoScalingGroupSubnetIds: !Join [ ",", [ !GetAtt NetworkingStack.Outputs.PublicSubnet1Id, !GetAtt NetworkingStack.Outputs.PublicSubnet2Id ] ]
        Route53HostedZone: !GetAtt NetworkingStack.Outputs.Route53HostedZone


Outputs:
  LoadBalancerDNSName:
    Description: DNS name of the load balancer
    Value: !GetAtt ComputingStack.Outputs.LoadBalancerDNSName
